name: vcpkg-test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          git clone https://github.com/microsoft/vcpkg
          cd vcpkg
          bootstrap-vcpkg.bat
          vcpkg install gtkmm --triplet=x64-windows
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-windows-latest
          path: |
            ./installed/
