name: vcpkg-test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        pkg: ["gtk3","gtk","gtkmm","ffmpeg","ffmpeg[all]"]
        target: ["x86-windows","x86-windows-static","x64-windows","x64-windows-static"]
    runs-on: windows-latest
    if: contains(matrix.pkg, "gtk") && contains(matrix.target, "static") || !contains(matrix.pkg, "gtk")
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          cd \
          dir
          git clone https://github.com/microsoft/vcpkg
          cd vcpkg
          bootstrap-vcpkg.bat
          vcpkg install ${{ matrix.pkg }} --triplet=${{ matrix.target }}
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-${{ matrix.pkg }}
          path: |
            \vcpkg\installed\
